[platformio]
default_envs = cardputer-adv, esp32s3

; Environment for Wokwi Simulator
[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

lib_deps =
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit ST7735 and ST7789 Library @ ^1.10.4
    bblanchon/ArduinoJson @ ^7.0.4

build_flags =
    -D CORE_DEBUG_LEVEL=3
    -D ARDUINO_USB_CDC_ON_BOOT=0
    -D TARGET_WOKWI_SIMULATOR

; Physical Hardware environment for M5Stack Cardputer-Adv (SKU: K132-Adv)
[env:cardputer-adv]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
upload_speed = 1500000
monitor_speed = 115200

board_upload.flash_size = 8MB
board_build.partitions = default_8MB.csv

lib_deps =
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit ST7735 and ST7789 Library @ ^1.10.4
    bblanchon/ArduinoJson @ ^7.0.4

build_flags =
    -D ESP32S3
    -D CORE_DEBUG_LEVEL=3
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    -D TARGET_M5_CARDPUTER_ADV
